name: CMake
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PICO_SDK_FETCH_FROM_GIT: ON

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fiam/arm-none-eabi-gcc@v1.0.2 
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/out/build

    - name: Build
      run: cmake --build ${{github.workspace}}/out/build 

      
